### PR TITLE
Simplifies .travis.yml file to make it work.

### PR DESCRIPTION
**Pull request by redwarp**
(Travis seems to not like oracle jdk 8 anymore)

### CODE REVIEW

**Comment by redwarp** [comment]
https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038

**Comment by cortinico** [comment]
Why are we specifying the JDK to install?

Isn't that automatically configured by the `android` language on Travis?
https://docs.travis-ci.com/user/languages/android/

**Comment by redwarp** [comment]
@cortinico good question. Let's try to remove it. Anyway, problem seem to be now in the installation of android tools.

**Comment by redwarp** [comment]
After my changes, it passes on my fork: https://travis-ci.org/Yelp/bento/builds/565966909

**Review by cortinico — APPROVED** [review]

**Pull request merged**
