### PR TITLE
docs: Fixed typo in wiki example description

### PR DESCRIPTION
**Pull request by coltin**

### CODE REVIEW

**Comment by redwarp** [comment]
So @coltin  we decided to embrace conventional commits ;-) So if you amend your commit message, should be good

**Comment by coltin** [comment]
@redwarp Never heard of that before, neat! Fixed

**Comment by redwarp** [comment]
@coltin techically, this should not be `fix:` but `doc:`

**Comment by redwarp** [comment]
So it should be reworded: a "fix" will show up in the  changelog.

**Review by redwarp — COMMENTED** [review]
Good to go

**Pull request merged**
